# Generated by Django 4.1.7 on 2023-04-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='profile_pics'),
        ),
    ]
